version: '3'

services:
  mysql:
    container_name: mysql
    restart: always
    image: wonderlandpark/mariadb-mroonga:latest
    hostname: mysql
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/mysql-beta:/var/lib/mysql
  mongo:
    container_name: mongo
    restart: always
    image: mongo:5.0
    hostname: mongo
    env_file:
      - .env
    volumes:
      - /home/ubuntu/mongo-beta:/data/db
  bot:
    container_name: bot
    restart: always
    image: 397554924689.dkr.ecr.ap-northeast-2.amazonaws.com/dskr
    links:
      - mongo
    env_file:
      - .env
  web:
    container_name: web
    restart: always
    image: 397554924689.dkr.ecr.ap-northeast-2.amazonaws.com/koreanlist
    ports:
      - 4000:3000
    links:
      - mysql
      - mongo
    env_file:
      - .env.beta.production.local
    deploy:
      resources:
        limits:
          memory: 500M
